import { Artifact } from "../artifacts";
import { Role } from "../roles";

export interface RunProgress {
  runId: string;
  featureRequest: string;
  roles: Role[];
  completedRoles: Map<string, { agent: string; durationMs: number }>;
  status: "running" | "done" | "failed" | "cancelled";
  error?: string;
  prUrl?: string;
}

export function formatProgressComment(run: RunProgress): string {
  const lines: string[] = [];

  lines.push(`## :building_construction: Council Pipeline`);
  lines.push("");
  lines.push(`> ${run.featureRequest}`);
  lines.push("");
  lines.push(`Run: \`${run.runId}\``);
  lines.push("");

  lines.push("| Role | Status | Agent | Duration |");
  lines.push("|------|--------|-------|----------|");

  for (const role of run.roles) {
    const completed = run.completedRoles.get(role.name);
    if (completed) {
      const secs = Math.round(completed.durationMs / 1000);
      lines.push(`| ${role.title} | :white_check_mark: Done | \`${completed.agent}\` | ${secs}s |`);
    } else if (run.status === "running" && !completed) {
      const isNext = !run.completedRoles.has(role.name) &&
        run.roles.findIndex((r) => r.name === role.name) ===
        run.completedRoles.size;
      if (isNext) {
        lines.push(`| ${role.title} | :hourglass_flowing_sand: Running... | — | — |`);
      } else {
        lines.push(`| ${role.title} | :white_circle: Pending | — | — |`);
      }
    } else {
      lines.push(`| ${role.title} | :white_circle: Pending | — | — |`);
    }
  }

  lines.push("");

  if (run.status === "failed" && run.error) {
    lines.push(`:x: **Failed:** ${run.error}`);
    lines.push("");
  }

  if (run.status === "done" && run.prUrl) {
    lines.push(`:rocket: **PR created:** ${run.prUrl}`);
    lines.push("");
  }

  if (run.status === "cancelled") {
    lines.push(`:stop_sign: Pipeline cancelled.`);
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`_Generated by [council-cli](https://github.com/council-cli)_`);

  return lines.join("\n");
}

export function formatPRBody(featureRequest: string, artifacts: Artifact[], totalMs: number, accepted: boolean): string {
  const lines: string[] = [];
  const mins = Math.round(totalMs / 60000);
  const secs = Math.round((totalMs % 60000) / 1000);

  lines.push(`## Summary`);
  lines.push("");
  lines.push(`> ${featureRequest}`);
  lines.push("");
  lines.push(`Pipeline completed in **${mins}m ${secs}s**. CEO decision: **${accepted ? "Approved :white_check_mark:" : "Needs Work :warning:"}**`);
  lines.push("");
  lines.push(`## Artifacts`);
  lines.push("");
  lines.push(`| Artifact | Role | Size |`);
  lines.push(`|----------|------|------|`);

  for (const a of artifacts) {
    const kb = (a.content.length / 1024).toFixed(1);
    lines.push(`| ${a.type} | ${a.producerRole} | ${kb}KB |`);
  }

  lines.push("");
  lines.push(`See comments below for detailed artifacts from each role.`);
  lines.push("");
  lines.push(`---`);
  lines.push(`_Generated by [council-cli](https://github.com/council-cli)_`);

  return lines.join("\n");
}

export function formatArtifactComment(artifact: Artifact): string {
  const LABELS: Record<string, string> = {
    spec: "Product Spec (from PM)",
    design: "Technical Design (from Architect)",
    code: "Implementation Diff (from Developer)",
    em_report: "Engineering Manager Report",
    qa_report: "QA Report (from QA Engineer)",
    decision: "CEO Decision",
  };

  const label = LABELS[artifact.type] ?? artifact.type;
  const kb = (artifact.content.length / 1024).toFixed(1);
  const lines: string[] = [];

  lines.push(`## ${label}`);
  lines.push("");

  if (artifact.content.length > 500) {
    lines.push(`<details>`);
    lines.push(`<summary>Click to expand (${kb}KB)</summary>`);
    lines.push("");
    if (artifact.type === "code") {
      lines.push("```diff");
      lines.push(artifact.content.slice(0, 60000));
      lines.push("```");
    } else {
      lines.push(artifact.content.slice(0, 60000));
    }
    lines.push("");
    lines.push(`</details>`);
  } else {
    if (artifact.type === "code") {
      lines.push("```diff");
      lines.push(artifact.content);
      lines.push("```");
    } else {
      lines.push(artifact.content);
    }
  }

  lines.push("");
  lines.push(`_Agent: \`${artifact.producerAgent}\`_`);

  return lines.join("\n");
}

export function formatStatusComment(runId: string, status: string, completedRoles: string[], totalRoles: number, error?: string): string {
  const lines: string[] = [];

  lines.push(`## :bar_chart: Pipeline Status`);
  lines.push("");
  lines.push(`Run: \`${runId}\``);
  lines.push(`Status: **${status}**`);
  lines.push(`Progress: ${completedRoles.length}/${totalRoles} roles completed`);

  if (completedRoles.length > 0) {
    lines.push(`Completed: ${completedRoles.join(" → ")}`);
  }

  if (error) {
    lines.push("");
    lines.push(`:x: Error: ${error}`);
  }

  return lines.join("\n");
}

export function formatErrorComment(error: string): string {
  return `:x: **Council Error**\n\n${error}\n\n_Use \`@council-bot /retry\` to try again._`;
}

export function formatHelpComment(botUsername: string): string {
  return `## :scales: Council Bot Commands

| Command | Description |
|---------|-------------|
| \`@${botUsername} /company <feature>\` | Run full AI company pipeline (PM → Architect → Dev → EM → QA → CEO) |
| \`@${botUsername} /compare <task>\` | Compare multiple agents on a single task |
| \`@${botUsername} /status\` | Show pipeline status for this issue |
| \`@${botUsername} /retry\` | Retry the last failed pipeline |
| \`@${botUsername} /cancel\` | Cancel a running pipeline |
| \`@${botUsername} /help\` | Show this help |

**Options:**
- \`--agents=claude:claude-sonnet-4-6,codex:o3-mini\` — specify agents
- \`--roles=pm,architect,developer\` — select pipeline roles`;
}
